### ISSUE TITLE
Regular crash / Icons gone after crash

### ISSUE THREAD

**Issue by ghost** [WeeJeWel/com.mi.flora#1]
Metadata

Homey Version:1.5.8
Homey Log Code:
Smartphone Platform: Android
Smartphone App Version:

If related to a Homey App: Mi FLora
Homey App Version: 1.0.3
Homey App Log Code: 454bd040-cb2f-4e6d-97df-3967c02150c4
Affected Devices (preferably product codes): Xiaomi 4 in 1 Flower Plant Soil Monitor

What did you try to achieve?
Regular app crash

What did you expect as result?
That the app doesn't crash. ;)

![flora 1](https://user-images.githubusercontent.com/2519741/37564725-181ac692-2a9c-11e8-8805-68d5a7b0f87c.PNG)
![flora 2](https://user-images.githubusercontent.com/2519741/37564726-1b2b3ea2-2a9c-11e8-97ff-0a3015642ebb.PNG)

**Comment by WeeJeWel** [comment]
How does this look after a refresh?

**Comment by ghost** [comment]
After a few crash/restarts the icons reappeared again.

**Comment by Dijker** [comment]
Probably the same here?
The unique log ID is: 8833b59a-048a-4613-8779-e4ead22e28df

**Comment by klappenbach** [comment]
Same here, crashes every day.

**Comment by WeeJeWel** [comment]
@Dijker Please update your Homey version to >=1.5.9.
@gabbah Can you send me a log?

**Comment by klappenbach** [comment]
@WeeJeWel I've sent developer logs every time it has crashed... so about four or five so far... Do you need anything else?
This is on Homey version 1.5.8. Is it more stable with 1.5.9?

**Comment by WeeJeWel** [comment]
Yes. I haven't seen a crash on Homey v1.5.9, which contained a Bluetooth fix.

**Comment by klappenbach** [comment]
Ok cool, will update.
